### ISSUE TITLE
Register port number

### ISSUE THREAD

**Issue by mjtrangoni** [lovoo/ipmi_exporter#22]
Hi!
I just wanted to point you out, that you should reserve a port number [here](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) as referenced in [writing_exporters/#port-numbers](https://prometheus.io/docs/instrumenting/writing_exporters/#port-numbers).  Thanks!

**Comment by carlbennett** [comment]
I just added it: [21ba487...f0084f0](https://github.com/prometheus/prometheus/wiki/Default-port-allocations/_compare/21ba4877a29c2cf974256266325e30f2f950898e...f0084f0adba5cd19f4b2a0ccf416490a23247901)
