### ISSUE TITLE
Grafana Dashboards

### ISSUE THREAD

**Issue by mjtrangoni** [lovoo/ipmi_exporter#24]
Hi,

I would be nice to have an open-source Grafana Dashboard [here](https://grafana.com/dashboards?dataSource=prometheus) and at the same time, to link it or make some previews in [README.md](README.md)

**Comment by carlbennett** [comment]
I created a dashboard for it myself. It could probably use some polishing, but here you go.


[IPMI Overview-1501185856351.json.zip](https://github.com/lovoo/ipmi_exporter/files/1181116/IPMI.Overview-1501185856351.json.zip)

**Comment by SqiSch** [comment]
It would be nice when you add the json as PR in the repository. For example in the directory dashboards/grafana,json, so other have the chance to use/modify it.

**Comment by carlbennett** [comment]
Made a pull request: #30

**Comment by carlbennett** [comment]
#30 has been merged. I believe this issue can be closed.

**Comment by SqiSch** [comment]
done with #30
